from opentelemetry import trace, metrics
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.trace import TracerProvider

# Configure OpenTelemetry
trace.set_tracer_provider(TracerProvider())
metrics.set_meter_provider(MeterProvider())

# Get the Tracer and Meter
tracer = trace.get_tracer("openai.tracer")
meter = metrics.get_meter("openai.meter")

# Create Counter instruments
tokens_counter = meter.create_counter(
    "tokens_counter",
    description="The number of tokens generated by model",
    unit="1",
)

prompt_tokens_counter = meter.create_counter(
    "prompt_tokens",
    description="The number of prompt tokens in a chat completion",
    unit="1",
)

completion_tokens_counter = meter.create_counter(
    "completion_tokens",
    description="The number of completion tokens in a chat completion",
    unit="1",
)
